project:
  type: book
  output-dir: docs  

number-depth: 0

execute:
  freeze: auto

book:
  favicon: "./img/logo.png"
  cover-image: "./img/logo.png"
  author: "明数科技"
  back-to-top-navigation: true
  page-navigation: true
  search: true
  # reader-mode: true
  repo-url: https://github.com/jackkkchen/python-book
  

  sidebar:
    style: "docked"
    background: light
  #   tools:
  #     - icon: twitter
  #       href: https://twitter.com
  #     - icon: github
  #       menu:
  #         - text: Source Code
  #           url:  https://code.com
  #         - text: Report a Bug
  #           url:  https://bugs.com
            



  # date: "5/25/2023"
  # repo-actions: [edit]
  # downloads: [pdf, epub]
  # sharing: [twitter, facebook]

  chapters:
    - index.qmd
    - intro.qmd
    - 环境搭建.qmd
    - Python入门小白教程.qmd
    - part: "Pandas快速入门"
      chapters: 
        - 安装.ipynb
        - pandas处理什么样的数据.ipynb
        - 导入&导出数据.ipynb
        - 更好的数据可视化.ipynb
        - 添加新列.ipynb
        - zhizai.qmd
        - time_data.qmd
        - txt_data.qmd
highlight-style: pygments

format:
  html:
    theme: cosmo
    cover-image: "./img/logo.png"
    code-copy: true
    code-link: true
  pdf: default
  # ipynb:
  #   number-sections: true




