project:
  type: book
  output-dir: docs  

execute:
  freeze: auto

book:
  favicon: "./img/logo.png"
  cover-image: "./img/logo.png"
  author: "明数科技"
  date: "5/25/2023"
  search: true
  repo-url: https://github.com/jackkkchen/python-book
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  page-navigation: true


  chapters:
    - index.qmd
    - intro.qmd
    - 环境搭建.qmd
    - Python入门小白教程.qmd
    - part: "Pandas入门教学"
      chapters:
        - 安装.ipynb
        - 快速入门.ipynb
        - time_data.qmd
        - txt_data.qmd

format:
  html:
    theme: cosmo
    cover-image: "./img/logo.png"
    code-link: true
  # ipynb:
  #   number-sections: true




