project:
  type: book
  output-dir: docs  

crossref:
  chapters: false

execute:
  freeze: auto

book:
  favicon: "./img/logo.png"
  cover-image: "./img/logo.png"
  author: "明数科技"
  date: "5/25/2023"
  search: true
  repo-url: https://github.com/jackkkchen/python-book
  repo-actions: [edit]
  downloads: [pdf, epub]
  sharing: [twitter, facebook]
  page-navigation: true

  chapters:
    - index.qmd
    - intro.qmd
    - 环境搭建.qmd
    - Python入门小白教程.qmd
    - part: "Pandas快速入门"
      chapters: 
        - 安装.ipynb
        - pandas处理什么样的数据.ipynb
        - 导入&导出数据.ipynb
        - 更好的数据可视化(Plotly).ipynb
        - 添加新列.ipynb
        - zhizai.qmd
        - time_data.qmd
        - txt_data.qmd

format:
  html:
    theme: cosmo
    cover-image: "./img/logo.png"
    code-link: true
  # ipynb:
  #   number-sections: true




