project:
  type: book
  output-dir: docs  

number-depth: 0

execute:
  freeze: auto

book:
  title: "Python新手文档"
  author: "明数科技"
  favicon: "./img/logo.png"
  cover-image: "./img/logo.png"
  back-to-top-navigation: true
  page-navigation: true
  search: true
  # reader-mode: true  

  # sidebar:
  #   style: "docked"
  #   background: light
  #   tools:
  #     - text: Bilibili 
  #       href: https://space.bilibili.com/22770928?spm_id_from=333.33.b_73656375726974794f75744c696e6b.1
  #     - icon: github
  #       url:  https://github.com/jackkkchen/python-book

  # date: "5/25/2023"
  repo-url: https://github.com/jackkkchen/python-book
  repo-actions: [edit]
  downloads: [pdf, epub]
  # sharing: [twitter, facebook]

  chapters:
    - index.qmd
    - intro.qmd
    - 环境搭建.qmd
    - Python入门小白教程.qmd
    - part: "Pandas快速入门"
      chapters: 
        - 安装.ipynb
        - pandas处理什么样的数据.ipynb
        - 导入&导出数据.ipynb
        - 选取数据.ipynb
        - 添加新列.ipynb
        - Pandas计算重塑合并 修改版.ipynb
        - time_data.qmd
        - txt_data.qmd
        - 更好的数据可视化.ipynb
        

highlight-style: pygments

format:
  html:
    theme: cosmo
    cover-image: "./img/logo.png"
    code-copy: true
    code-link: true
  # pdf: default
  # ipynb:
  #   number-sections: true




